-- =========================================================
-- V1.6  AI Learning Module
-- =========================================================
-- Purpose:
--   Creates study tool infrastructure powered by AI:
--   - quiz / question (AI-generated multiple choice quizzes)
--   - quiz_attempt / quiz_answer (user quiz attempts)
--   - flashcard / flashcard_progress (spaced-repetition flashcards)
--   - study_report (AI-generated study reports)
--
-- Dependencies:
--   V1.0  (account references)
--   V1.2  (document references)
--
-- Notes:
--   Quiz and flashcard content is generated by Gemini API
--   and cached in these tables to avoid redundant AI calls.
--   Spaced repetition tracking via flashcard_progress
--   (next_review_at for SRS scheduling).
--
-- =========================================================

CREATE TABLE quiz (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id     UUID NOT NULL,
    title           VARCHAR(255) NOT NULL,
    generated_by_ai BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_quiz_document FOREIGN KEY (document_id) REFERENCES document(id) ON DELETE CASCADE
);
CREATE INDEX idx_quiz_document ON quiz(document_id);

CREATE TABLE question (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quiz_id        UUID NOT NULL,
    content        TEXT NOT NULL,
    option_a       TEXT,
    option_b       TEXT,
    option_c       TEXT,
    option_d       TEXT,
    correct_answer VARCHAR(1),
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_question_quiz FOREIGN KEY (quiz_id) REFERENCES quiz(id) ON DELETE CASCADE,
    CONSTRAINT ck_question_answer CHECK (correct_answer IN ('A','B','C','D'))
);
CREATE INDEX idx_question_quiz ON question(quiz_id);

CREATE TABLE quiz_attempt (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quiz_id         UUID NOT NULL,
    account_id      UUID NOT NULL,
    score           INTEGER,
    total_questions INTEGER,
    status          VARCHAR(20) NOT NULL DEFAULT 'in_progress',
    started_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMP,
    CONSTRAINT fk_attempt_quiz    FOREIGN KEY (quiz_id)    REFERENCES quiz(id)   ON DELETE CASCADE,
    CONSTRAINT fk_attempt_account FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE
);
CREATE INDEX idx_attempt_quiz    ON quiz_attempt(quiz_id);
CREATE INDEX idx_attempt_account ON quiz_attempt(account_id);

CREATE TABLE quiz_answer (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    attempt_id      UUID NOT NULL,
    question_id     UUID NOT NULL,
    selected_answer VARCHAR(1),
    is_correct      BOOLEAN,
    answered_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_answer_attempt  FOREIGN KEY (attempt_id)  REFERENCES quiz_attempt(id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_question FOREIGN KEY (question_id) REFERENCES question(id)    ON DELETE CASCADE,
    CONSTRAINT ck_answer_value    CHECK (selected_answer IN ('A','B','C','D')),
    CONSTRAINT uk_answer UNIQUE (attempt_id, question_id)
);
CREATE INDEX idx_answer_attempt ON quiz_answer(attempt_id);

CREATE TABLE flashcard (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id     UUID NOT NULL,
    front_content   TEXT NOT NULL,
    back_content    TEXT NOT NULL,
    generated_by_ai BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_flashcard_document FOREIGN KEY (document_id) REFERENCES document(id) ON DELETE CASCADE
);
CREATE INDEX idx_flashcard_document ON flashcard(document_id);

CREATE TABLE flashcard_progress (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    flashcard_id     UUID NOT NULL,
    account_id       UUID NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'new',
    review_count     INTEGER NOT NULL DEFAULT 0,
    last_reviewed_at TIMESTAMP,
    next_review_at   TIMESTAMP,
    CONSTRAINT fk_progress_flashcard FOREIGN KEY (flashcard_id) REFERENCES flashcard(id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_account   FOREIGN KEY (account_id)   REFERENCES account(id)   ON DELETE CASCADE,
    CONSTRAINT uk_progress UNIQUE (flashcard_id, account_id)
);
CREATE INDEX idx_progress_account   ON flashcard_progress(account_id);
CREATE INDEX idx_progress_flashcard ON flashcard_progress(flashcard_id);

CREATE TABLE study_report (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID NOT NULL,
    account_id  UUID NOT NULL,
    title       VARCHAR(255) NOT NULL,
    content     TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_report_document FOREIGN KEY (document_id) REFERENCES document(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_account  FOREIGN KEY (account_id)  REFERENCES account(id)  ON DELETE CASCADE
);
CREATE INDEX idx_report_doc ON study_report(document_id);
