ALTER TABLE account DROP COLUMN IF EXISTS storage_quota_gb;
ALTER TABLE account DROP COLUMN IF EXISTS ai_questions_quota;
ALTER TABLE account ADD COLUMN IF NOT EXISTS plan VARCHAR(50) NOT NULL DEFAULT 'FREE';
